# Generated by Django 3.1.5 on 2021-03-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210319_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
