# Generated by Django 3.1.5 on 2021-03-19 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_product_product_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('product_Main_Img', models.ImageField(blank=True, default='product1.png', null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productimage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.productimage'),
        ),
    ]
