# Generated by Django 3.1.5 on 2021-03-23 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customeraddress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customeraddress'),
        ),
    ]
