# Generated by Django 3.1.5 on 2021-03-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customer_customeraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customeraddress',
        ),
        migrations.AddField(
            model_name='customer',
            name='customeraddress',
            field=models.ManyToManyField(blank=True, to='accounts.CustomerAddress'),
        ),
    ]
