# Generated by Django 3.1.5 on 2021-03-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210324_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='name',
            field=models.CharField(default='Address 1', max_length=200, null=True),
        ),
    ]
