# Generated by Django 2.0.13 on 2021-07-30 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_auto_20210329_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Address 1', max_length=200, null=True)),
                ('check_notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_completion', models.DateTimeField(auto_now_add=True, null=True)),
                ('form_note', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Quarantine', 'Quarantine'), ('Scrap', 'Scrap')], max_length=200, null=True)),
                ('SafetyCheck', models.ManyToManyField(blank=True, to='accounts.SafetyCheck')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customeraddress',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productimage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
