# Generated by Django 2.0.13 on 2021-08-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210730_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyform',
            name='date_completion',
            field=models.DateTimeField(null=True),
        ),
    ]
