# Generated by Django 2.0.13 on 2021-08-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210803_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyform',
            name='status',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Quarantine', 'Quarantine'), ('Scrap', 'Scrap'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
    ]
